name: Continuous integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [ruby-3.0, ruby-3.1, ruby-3.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby & Execute 'bundle install'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Test
        run: |
          ruby -v
          bin/rspec

  test-flaky:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [jruby-9.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby & Execute 'bundle install'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Test
        run: |
          ruby -v
          bin/rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby & Execute 'bundle install'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run RuboCop
        run: |
          ruby -v
          bin/rubocop
